runtime: nodejs
env: flex

env_variables:
  NODE_ENV: "production"
#  DEBUG: "loopback:datasource"

beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: marukyo-api:asia-south1:marukyo
